### ISSUE TITLE
parameter -mods

### ISSUE THREAD

**Issue by j2ghz** [DerAtrox/Arma3LauncherLib#3]
https://github.com/DerAtrox/Arma3LauncherLib/blob/v1.0.0-rc4/Arma3LauncherLib/Model/ArmaLauncher.cs#L91
The parameter should be `-mod`
Source: https://community.bistudio.com/wiki/Arma_3_Startup_Parameters

**Comment by DerAtrox** [comment]
fixed with 9066d4c
